version: 2

models:
  - name: validated_emails
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_validated_emails')
     
    columns:
      - name: email
        tests:
          - re_data.valid_string:
              macro: valid_email
              where_cond: is_valid = true

  - name: validated_numbers
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_validated_numbers')

    columns:
      - name: number
        tests:
          - re_data.valid_string:
              macro: valid_number
              where_cond: is_number = true

          - re_data.valid_string:
              macro: valid_number_decimal_point
              where_cond: is_number_decimal_point = true

  - name: validated_date_and_time
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_validated_date_and_time')

  - name: validated_ips
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_validated_ips')
  
  - name: validated_uuids
    tests:
      - dbt_utils.equality:
          compare_model: ref('expected_validated_uuids')