version: 2

models:
  - name: buy_events
    tests:
      - re_data.in_range:
          metric: row_count
          min_value: 0
          max_value: 10

    columns:
      - name: value1
        tests:
          - not_null
          - re_data.in_range:
              metric: nulls_percent
              min_value: 0
              max_value: 10
          - re_data.in_range:
              metric: min
              min_value: 0
              max_value: 1000




        